### ISSUE TITLE
Config and private keys

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/stripe_checkout#1]
Backdroppers,

Is it okay to do private API keys (e.g. public and private secret keys in Stripe's terminology) as regular text fields in the form, or is there a better option?

https://github.com/backdrop-contrib/stripe_checkout/blob/master/stripe_checkout.admin.inc#L92-L120

**Comment by Gormartsen** [comment]
@laryn I understand your concern.

It is sensitive information like password field.
I use textfield, because it is necessary to see this value.

Also, I can suggest implementing read-only feature via store this values in settings.php.

You can see it here: https://github.com/backdrop-contrib/githubapi/blob/master/githubapi.admin.inc#L10

**Comment by laryn** [comment]
Thanks!

I like how you separated the secret settings into a separate config. Then if the public settings are exposed for import/export you don't have to worry about the private info being there.

**Comment by laryn** [comment]
Closing this issue as this module is no longer maintained. Stripe development is now centering around
the [Stripe](https://github.com/backdrop-contrib/stripe) module, including the bundled `webform_stripe` functionality.
